### ISSUE TITLE
Phase 1

### ISSUE THREAD

**Issue by sypher-in-the-snow** [camhart/ultimatetraffic#17]
If there is a long line of cars heading toward a light that is red, when the light changes to green, the cars' speed does not change until passing the light.  This causes significant delay, their command speed should possibly be updated upon the changing of a light.

**Comment by urrry1** [comment]
If you un comment the call to intermediate algorithm, that should fix that. I wrote it for that specific purpose. It gets called on all cars applicable every time a light goes green.

**Comment by camhart** [comment]
Brian can the intermediateAlgorithm use the new iterator I made?  Does it just need to go through cars in order to work?

Here's the error I get now with it uncommented.

```
Exception in thread "main" java.util.ConcurrentModificationException
    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
    at java.util.LinkedList$ListItr.next(LinkedList.java:888)
    at simulator.models.stoplights.Phase1StopLight.CallIntermediateAlgorithmOnAllCars(Phase1StopLight.java:90)
    at simulator.models.stoplights.Phase1StopLight.handleLightColors(Phase1StopLight.java:32)
    at simulator.models.stoplights.StopLight.iterate(StopLight.java:168)
    at simulator.Simulator.run(Simulator.java:273)
    at simulator.Simulator.main(Simulator.java:367)
```

I'm pretty sure you are aware of this already as I recall you mentioning it in an email.  I'll see what I can figure out with it.

**Comment by urrry1** [comment]
It needs to be called on each car in the lights lanes using your new
iterator.

**Comment by camhart** [comment]
Are you able to get on gitter right now?

**Comment by urrry1** [comment]
Before the re factor, that's what I did in the function
callIntermediateAlgorithm. Look at that to see how it works.

**Comment by camhart** [comment]
When you have time, could you give an explaination of what intermediateAlgorithm(CarManager car, StopLight currentLightArg) does exactly?  This might be something better to do in person if it's complicated.  I'll try to sort through it tonight, but it's a bit of a complicated beast.

**Comment by urrry1** [comment]
I'm pretty sure it's literally a copy of the algorithm, but with some
features removed. The only new feature might be a forced lane change (with
the original algorithm the actual move to the new object takes/took place
after the algorithm in the iterate code, I believe.)

**Comment by camhart** [comment]
So the reason why the method call to algorithm allows lane changes (and doesn't throw a ConcurrentModificationException) is because it only ever works with the last car on the list.  Since that's the case, it changes lanes but then we never call the next() method on the iterator object (so ConcurrentModificationException doesn't get thrown).

The intermediate algorithm is trying to get cars to change lanes in the middle of the list of cars.  The assumption was made initially that we would only change lanes right as we pass under the stop light.  The system was built with that in mind...  So for now, I don't see an easy way possible for the intermediate algorithm to allow cars to change lanes.

Due to the time constraints we have, I suggest we abandon lane changing within the intermediate algorithm and just let the intermediate algorithm change speed based on the car in front of them.

**Comment by urrry1** [comment]
I completely agree. Allowing lane changes between lights wouldn't likely
make any noticeable change for our results anyway, so I definitely vote we
just remove or comment out that section of the intermediate algorithm.

**Comment by grossie** [comment]
I also agree. That sounds good.

**Comment by camhart** [comment]
Should be taken care of now that the intermediate algorithm runs on every iteration.  Though we may want to adjust how frequently it runs.
